### ISSUE TITLE
Renderer - only HUD and Sky is rendered

### ISSUE THREAD

**Issue by doclulle** [3dfxdev/EDGE#78] opened 2020-03-30 15:45 UTC
HI,
I compiled Edge yesterday  a few times. No mater what I change: the .exe only renders sky(box) and HUD, Menu etc. Everything else is black.

LOG:

Log file created at 05:05 PM on 30/Mar/2020]
[Debug file created at 05:05 PM on 30/Mar/2020]

EDGE (x64) 2.1.0pre-87-gf20e200d0 compiled on Mar 30 2020 at 17:03:35
EDGE homepage is at http://EDGE.sourceforge.net/
EDGE Wiki is at http://3dfxdev.net/edgewiki/
EDGE forums are located at http://tdgmods.net/smf
EDGE problems should be reported via https://github.com/3dfxdev/hyper3DGE/issues
EDGE is based on id Tech by id Software http://www.idsoftware.com/
Executable path: 'D:\Source\EDGE\BUILD64\Release'
Command-line Options:
  D:\Source\EDGE\BUILD64\Release\EDGE.exe 
==============================================================================
E_ShowCPU: Getting CPU information...
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Family 6, Model 60, Stepping 3
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
==============================================================================
M_LoadDefaults from .\EDGE.ini
- System startup begun.
* Optimus GPU setting not set.
I_StartupGraphics: initialisation OK
Desktop resolution: 1920x1200
==============================================================================
Getting SDL2 Version Information...
EDGE compiled against SDL version 2.0.10 ...
But EDGE is linking against SDL version 2.0.10.
==============================================================================
I_StartupControl: 1 joysticks found.
SDL_Audio_Driver: default
I_StartupSound: trying 48000 Hz, 32 bit Stereo
I_StartupSound: Success @ 48000 Hz, 32 bit Stereo
I_StartupMUS: Couldn't load the midi mixer
I_StartupMusic: OPL Init OK
** FindTimidityConfig:
tim_player_c: Cannot find Timidity config file!
I_StartupMusic: Timidity Init FAILED
>> LocalHostName: Loot
>> LocalAddress: 192.168.56.1
>> LocalAddress: 192.168.100.26
I_StartupNetwork: Initialised OK.
Available Resolutions:
  1920x1200 @ 24 FS   1920x1080 @ 24 FS   1680x1050 @ 24 FS 
  1600x1200 @ 24 FS   1600x1024 @ 24 FS   1600x 900 @ 24 FS 
  1440x 900 @ 24 FS   1360x 768 @ 24 FS   1280x1024 @ 24 FS 
  1280x 960 @ 24 FS   1280x 800 @ 24 FS   1280x 768 @ 24 FS 
  1280x 720 @ 24 FS   1152x 864 @ 24 FS   1024x 768 @ 24 FS 
   800x 600 @ 24 FS    720x 576 @ 24 FS    720x 480 @ 24 FS 
   640x 480 @ 24 FS    320x 200 @ 24 win   320x 240 @ 24 win
   400x 300 @ 24 win   512x 384 @ 24 win   640x 400 @ 24 win
   640x 480 @ 24 win   800x 600 @ 24 win  1024x 640 @ 24 win
  1024x 768 @ 24 win  1280x 720 @ 24 win  1280x 960 @ 24 win
  1440x 900 @ 24 win  1440x1080 @ 24 win  1600x1000 @ 24 win
  1600x1200 @ 24 win  1680x1050 @ 24 win  1920x1080 @ 24 win
  1920x1200 @ 24 win
- Changing Resolution...
R_InitialResolution setting up...
RGL_ReInit!
R_SoftInitResolution...
-  returning true.
OpenGL: Initializing Render Buffers (GLSL)...
==============================================================================
I_SetScreenSize: trying 1440x1080 24bpp (windowed)
==============================================================================
OpenGL Subsystem: Initialising...
RGL_LoadContextExtensions...
OpenGL: Collecting Extensions...
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1050 Ti/PCIe/SSE2
GL_VERSION: 3.1.0 NVIDIA 417.01 (Compatibility profile)
GL_SHADING_LANGUAGE_VERSION: 1.40 NVIDIA via Cg compiler
OpenGL: Implementation limits:
-Maximum texture size: 32768
-Maximum texture units: 32
-Maximum varying: 124
-MAximum clip planes: 8
OpenGL: Initializing Render Buffers (GLSL)...
==============================================================================
R_SoftInitResolution...
-  returning true.
- System startup done.
- Initialising DDF
==============================================================================
- IdentifyVersion()...
Added filename: .\doom.wad
IWAD BASE = [doom]
Added filename: .\edge.epk
  Adding .\doom.wad
   md5hash = 9db4b8a0...a279f73b
Levels 36, Internal GL nodes 0
FindCacheFilename: local_name = '.\doom.gwa'
FindCacheFilename: cache_name = '.\cache\doom-9DB4B8-A0D8BC.gwa'
FindCacheFilename: has_local=NO  has_cache=NO
Actual_GWA_filename: .\cache\doom-9DB4B8-A0D8BC.gwa
Building GL Nodes for: .\doom.wad
GB_BuildNodes: STARTED
# source: '.\doom.wad'
#   dest:  '.\cache\doom-9DB4B8-A0D8BC.gwa'
...
GLBSP: Total serious warnings: 0
GLBSP: Total minor warnings: 16
GLBSP: 
GLBSP: All levels were built successfully.
GB_BuildNodes: SUCCESS
...
Very odd..
lu

**Comment by usernameak** [comment] 2020-03-30 15:53
duplicate of #77. try building it from feature/renderer-upgrade branch

**Comment by doclulle** [comment] 2020-03-31 01:32
Thanks, that fixed it!
 ויְהִי אוֹר

**Comment by usernameak** [comment] 2020-03-31 01:44
> Thanks, that fixed it!
> ויְהִי אוֹר

so if it works, i should add check for -1 and fix some things up to make it work completely properly

**Comment by doclulle** [comment] 2020-03-31 22:35
Works fine. Even some new effects like smoke Ive never seen before.

**Comment by usernameak** [comment] 2020-03-31 23:44
> Works fine. Even some new effects like smoke Ive never seen before.
except broken loading screen

**Closed** 2020-04-01 00:04 UTC
